# Remove obsolete plugin binaries from this build's development output only.
cmake_minimum_required(VERSION 3.21)
file(REAL_PATH "${BUILD_ROOT}" _build_root)
file(REAL_PATH "${MODULE_DIR}" _module_dir)
cmake_path(IS_PREFIX _build_root "${_module_dir}" NORMALIZE _inside_build)
if (NOT _inside_build OR _module_dir STREQUAL _build_root)
    message(FATAL_ERROR "Module output must be inside the build directory: ${_module_dir}")
endif()
file(GLOB _module_binaries "${_module_dir}/*.dll")
foreach(_binary IN LISTS _module_binaries)
    get_filename_component(_name "${_binary}" NAME)
    if (NOT _name IN_LIST ENABLED_BINARIES)
        message(STATUS "Removing obsolete module binary: ${_name}")
        file(REMOVE "${_binary}")
    endif()
endforeach()
