# GNU Radio VOLK: installed dependency by default, with an optional source fallback.
if (MSVC)
    find_package(Volk CONFIG REQUIRED)
    if (TARGET Volk::volk)
        set(SDRPP_VOLK_TARGET Volk::volk)
    elseif (TARGET volk)
        set(SDRPP_VOLK_TARGET volk)
    else()
        message(FATAL_ERROR "The VOLK package did not provide Volk::volk or volk")
    endif()
else()
    set(SDRPP_VOLK_TARGET volk)
endif()
